apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-webdb-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-webdb-app
spec:
  source:
    git:
      url: https://github.com/bmullan-pivotal/spring-webdb
      ref:
        branch: main